sudo: required
services:
  - docker

before_install:
  - docker build -t fcleyssac/docker-react -f Dockerfile.dev .

script:
  - docker run fcleyssac/docker-react npm run test -- --coverage

deploy:
  provider: elastickbeanstalk
  region: eu-central-1
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-485205850455"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
